# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='open',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volum',
            field=models.BigIntegerField(null=True),
        ),
    ]
