# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyse', '0003_auto_20171213_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='volum',
            new_name='vol',
        ),
        migrations.AddField(
            model_name='stock',
            name='ma10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ma20',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ma5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='tor',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='vr',
            field=models.FloatField(null=True),
        ),
    ]
